//
// Created by R on 2020/2/5.
//

#ifndef POSTGRADUATEENTRANCEEXAMINATION_SORT_NODE_NODE_H
#define POSTGRADUATEENTRANCEEXAMINATION_SORT_NODE_NODE_H


typedef struct Node {
    int no;
    int score;
};


#endif //POSTGRADUATEENTRANCEEXAMINATION_SORT_NODE_NODE_H
